### ISSUE TITLE
Travis CI is failing to import pycs

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/SLTimer#35]
As seen [here](https://travis-ci.org/DarkEnergyScienceCollaboration/SLTimer/builds/143226643), for example. Not sure why this is happening - the pip install used to work just fine!

**Comment by jchiang87** [comment]
It's also failing to import the `coverage` module too.  I think the problem is that it is running the `nosetests` from the initial virtualenv setup (which is a python script that probably has its `#!` pointing to that python 2.7.9 install), whereas the `pip` and `python` you are running are coming from the miniconda distribution, which uses python 2.7.11.   Try adding `nose` to `requirements.txt`.  That should ensure you get the `nosetests` that can find those modules in the miniconda environment.

**Comment by drphilmarshall** [comment]
[Nailed it!](https://travis-ci.org/DarkEnergyScienceCollaboration/SLTimer/builds/143233716) Thanks @jchiang87

**Comment by jchiang87** [comment]
de rien.
